### ISSUE TITLE
https://lostechies.com/ is 404'in

### ISSUE THREAD

**Issue by jafin** [lostechies/blog#7]
Hi,  I'm not 100% certain this is the publishing site for https://lostechies.com/  but if so the site is currently 404ing.

**Comment by jmeridth** [comment]
@jafin thank you for letting us know.  We're addressing it now.

**Comment by jmeridth** [comment]
@jafin site is coming back up for me.  Can you please confirm?

**Comment by jafin** [comment]
All good here! Thanks.,

**Comment by jmeridth** [comment]
For the next LT person who finds this issue and wonders what the fix was.  I disable and re-enabled github pages on the repository.

![image](https://user-images.githubusercontent.com/35014/111628327-19b8a780-87be-11eb-9b70-b1e87cd898d8.png)
